### PR TITLE
Sponsors section

### PR DESCRIPTION
**Pull request by fauzieuy**
Image/Logo Sponsorship guidlines : 
- Must be at least 150 x 100 pixels
- Transparant background

Screenshoot :

### CODE REVIEW

**Comment by firewalker06** [comment]
Thanks for the guidelines. 

Since this will be reflected immediately after we merge this PR, how about showing confirmed Platinum sponsors and hide the others? We can use existing Go-Jek and BukaLapak logo.

**Comment by fauzieuy** [comment]
@firewalker06 ur welcome :+1: 

I think, We can use Jekyll's YML Data.

**Comment by firewalker06** [comment]
> I think, We can use Jekyll's YML Data.

@fauzieuy that would be better. So we can configure to show/hide easily.

**Comment by waruboy** [comment]
@fauzieuy cool! how about adding "sponsors" to nav?
Also, have you follow our proposal for logo size?
platinum, gold > 350 x 250px 
silver, 200 x 150px
digital, 150 x 100 px

**Comment by fauzieuy** [comment]
@firewalker06 done.

List of sponsors can add to each file yml at `_data/conf/` directory.
- platinum_sponsors.yml
- gold_sponsors.yml
- silver_sponsors.yml
- digital_sponsors.yml

**Comment by fauzieuy** [comment]
@waruboy
```
how about adding "sponsors" to nav?
```
oh, sorry I forgot that..

```
Also, have you follow our proposal for logo size?
platinum, gold > 350 x 250px
silver, 200 x 150px
digital, 150 x 100 px
```
fyi currently image sponsorship doesn't have an attribute of size.

I'll be back. ASAP...

**Comment by fauzieuy** [comment]
@waruboy add `sponsor` to nav & add attribute of size to each sponsors image

**Comment by waruboy** [comment]
Thanks bro. Btw masukin logo sponsor yang udah ada (BL + gojek) mau sekalian di PR ini apa gimana ni?

**Comment by fauzieuy** [comment]
@waruboy logo yang ada mesti di edit dulu bro sesuai ukurannya, gw ga jago edit gambar  :v:

**Comment by firewalker06** [comment]
@fauzieuy here, please use these (350x250)

bukalapak logo
go-jek logo

**Comment by fauzieuy** [comment]
@firewalker06 Thanks for the images, I've done.

**Pull request merged**
